[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
